-- BUDGET.dbo.BUDGET_GROUP definition

-- Drop table

-- DROP TABLE BUDGET.dbo.BUDGET_GROUP;

CREATE TABLE BUDGET.dbo.BUDGET_GROUP (
	Id int IDENTITY(1,1) NOT NULL,
	Bg_code nvarchar(50) COLLATE Thai_CI_AS NULL,
	Bg_name nvarchar(50) COLLATE Thai_CI_AS NULL,
	Bg_status int NULL,
	CONSTRAINT PK_BUDGET_GROUP PRIMARY KEY (Id)
);


-- BUDGET.dbo.Budget definition

-- Drop table

-- DROP TABLE BUDGET.dbo.Budget;

CREATE TABLE BUDGET.dbo.Budget (
	id int IDENTITY(1,1) NOT NULL,
	bu_no nvarchar(50) COLLATE Thai_CI_AS NULL,
	bu_desc nvarchar(50) COLLATE Thai_CI_AS NULL,
	bu_price numeric(18,2) NULL,
	ddate date NULL,
	status int NULL,
	dept_id nvarchar(50) COLLATE Thai_CI_AS NULL,
	bt_id nvarchar(50) COLLATE Thai_CI_AS NULL,
	type_income int NULL,
	ADDDATE datetime NULL,
	CONSTRAINT PK_Budget PRIMARY KEY (id)
);


-- BUDGET.dbo.Budget_name definition

-- Drop table

-- DROP TABLE BUDGET.dbo.Budget_name;

CREATE TABLE BUDGET.dbo.Budget_name (
	id int IDENTITY(1,1) NOT NULL,
	bn_code nvarchar(50) COLLATE Thai_CI_AS NULL,
	bn_name nvarchar(50) COLLATE Thai_CI_AS NULL,
	bn_status int NULL,
	CONSTRAINT PK_Budget_name PRIMARY KEY (id)
);


-- BUDGET.dbo.Budget_type definition

-- Drop table

-- DROP TABLE BUDGET.dbo.Budget_type;

CREATE TABLE BUDGET.dbo.Budget_type (
	id int IDENTITY(1,1) NOT NULL,
	bt_code nvarchar(50) COLLATE Thai_CI_AS NULL,
	bt_name nvarchar(50) COLLATE Thai_CI_AS NULL,
	bt_status int NULL,
	bg_id int NULL,
	bn_id int NULL,
	ADDDATE datetime NULL,
	CONSTRAINT PK_Budget_type PRIMARY KEY (id)
);


-- BUDGET.dbo.Department definition

-- Drop table

-- DROP TABLE BUDGET.dbo.Department;

CREATE TABLE BUDGET.dbo.Department (
	id int IDENTITY(1,1) NOT NULL,
	dept_name nvarchar(50) COLLATE Thai_CI_AS NULL,
	CONSTRAINT PK_Department PRIMARY KEY (id)
);


-- BUDGET.dbo.Employee definition

-- Drop table

-- DROP TABLE BUDGET.dbo.Employee;

CREATE TABLE BUDGET.dbo.Employee (
	id int IDENTITY(1,1) NOT NULL,
	emp_id varchar(50) COLLATE Thai_CI_AS NULL,
	emp_name varchar(150) COLLATE Thai_CI_AS NULL,
	emp_surname varchar(150) COLLATE Thai_CI_AS NULL,
	emp_dept varchar(50) COLLATE Thai_CI_AS NULL,
	emp_user varchar(50) COLLATE Thai_CI_AS NULL,
	emp_pass varchar(50) COLLATE Thai_CI_AS NULL,
	emp_status int DEFAULT 0 NULL,
	emp_createby varchar(50) COLLATE Thai_CI_AS NULL,
	emp_createdate datetime NULL,
	emp_updateby varchar(50) COLLATE Thai_CI_AS NULL,
	emp_updatedate datetime NULL,
	emp_email varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCSKID_EMP_FM nvarchar(50) COLLATE Thai_CI_AS NULL,
	CONSTRAINT PK_Employee PRIMARY KEY (id)
);


-- BUDGET.dbo.Key_run definition

-- Drop table

-- DROP TABLE BUDGET.dbo.Key_run;

CREATE TABLE BUDGET.dbo.Key_run (
	id int IDENTITY(1,1) NOT NULL,
	Key_run nvarchar(50) COLLATE Thai_CI_AS NULL,
	Dept_code nvarchar(50) COLLATE Thai_CI_AS NULL,
	CONSTRAINT PK_Key_run PRIMARY KEY (id)
);


-- BUDGET.dbo.PR_D definition

-- Drop table

-- DROP TABLE BUDGET.dbo.PR_D;

CREATE TABLE BUDGET.dbo.PR_D (
	FCDATASER char(4) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSKID char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUDATE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUTIME char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLUPDAPP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTAT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBRANCH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDEPT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSECT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCJOB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCORDERH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDDATE datetime DEFAULT getdate() NOT NULL,
	FCCOOR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFPDTYP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFTYPE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPRODTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSHOWCOMP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCROOTSEQ char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCFORMULAS char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPFORMULA char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPROD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUMSTD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNUMQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNBACKQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNPRICE decimal(20,6) DEFAULT 0 NOT NULL,
	FNDISCAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCPCN decimal(12,2) DEFAULT 0 NOT NULL,
	FCDISCSTR char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSEQ char(4) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATISOUT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNVATRATE decimal(10,1) DEFAULT 0 NOT NULL,
	FNVATAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FCLOT char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCISCHG char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCWHOUSE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMREMARK varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCCTRLSTOC char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATETY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEAFTERR char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSELTAG char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTDATETIME datetime DEFAULT getdate() NOT NULL,
	FIMILLISEC int DEFAULT 0 NOT NULL,
	FCPROJ char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNPRICEKE decimal(20,6) DEFAULT 0 NOT NULL,
	FNDISCAMTK decimal(20,4) DEFAULT 0 NOT NULL,
	FNXRATE decimal(20,8) DEFAULT 0 NOT NULL,
	FMREMARK2 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK3 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK4 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK5 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK6 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK7 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK8 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK9 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK10 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCIOTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTUM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTUMSTD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNSTUMQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNSTQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FDDELIVERY datetime DEFAULT NULL NULL,
	FCGVPOLICY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCAPPROVEB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDAPPROVE datetime DEFAULT NULL NULL,
	FCSTEP2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCMSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSUBBR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPLANT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTUPD datetime DEFAULT getdate() NULL,
	FCPROCHAIN char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTORE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPRIORITY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCGAG char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMTEXTKE varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FNPRQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FCTXID char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNPLANQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FCPDSTHPAC char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNDEFAPRIC decimal(20,6) DEFAULT 0 NOT NULL,
	FCSUBTXID char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNPACKQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNDOQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FCACCHART char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPRICE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELITIME char(5) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBUDCHART char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTXIDLINK char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTEDIT datetime DEFAULT NULL NULL,
	FCMAINJOBH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSUBJOBH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATEAP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCOUNTER char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU1ACC char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDATAIMP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRECALBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASRECAL datetime DEFAULT NULL NULL,
	FNWTAXRATE decimal(13,2) DEFAULT 0 NOT NULL,
	FNWTAXAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FNWTAXAMTK decimal(20,4) DEFAULT 0 NOT NULL,
	FCU1STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU2STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU1CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FNU2CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FMERRMSG varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCLID char(10) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBOICARD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBOIGROUP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATEBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORRECTB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTSRCUPD datetime NULL,
	FCSRCUPD char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREMLOCAT char(100) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMEXTRATAG text COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCORGCODE varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCCUACC varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCAPPNAME varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	CONSTRAINT PK__PR_D__8771A646B36CAB03 PRIMARY KEY (FCSKID)
);


-- BUDGET.dbo.PR_H definition

-- Drop table

-- DROP TABLE BUDGET.dbo.PR_H;

CREATE TABLE BUDGET.dbo.PR_H (
	FCDATASER char(4) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSKID char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUDATE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUTIME char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLUPDAPP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRFTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFTYPE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBRANCH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDEPT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSECT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCJOB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTAT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDDATE datetime DEFAULT getdate() NOT NULL,
	FDDUEDATE datetime DEFAULT NULL NULL,
	FDRECEDATE datetime DEFAULT NULL NULL,
	FCBOOK char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCODE char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFNO char(35) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNDISCAMT1 decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCAMT2 decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCAMTI decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCPCN1 decimal(12,2) DEFAULT 0 NOT NULL,
	FNDISCPCN2 decimal(12,2) DEFAULT 0 NOT NULL,
	FNDISCPCN3 decimal(12,2) DEFAULT 0 NOT NULL,
	FNAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FNAMT2 decimal(20,4) DEFAULT 0 NOT NULL,
	FCVATISOUT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNVATRATE decimal(10,1) DEFAULT 0 NOT NULL,
	FNVATAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FCCOOR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEMPL char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEMZONE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCISCASH char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNCREDTERM decimal(10,0) DEFAULT 0 NOT NULL,
	FCCREATEBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORRECTB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCANCELBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCACSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMMEMDATA varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCHASRET char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATDUE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRECVMAN char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATETY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEAFTERR char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSELTAG char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTDATETIME datetime DEFAULT getdate() NOT NULL,
	FIMILLISEC int DEFAULT 0 NOT NULL,
	FCSTEP2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPROJ char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDISCSTR char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCURRENCY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNAMTKE decimal(20,4) DEFAULT 0 NOT NULL,
	FNVATAMTKE decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCAMTK decimal(20,4) DEFAULT 0 NOT NULL,
	FNXRATE decimal(20,8) DEFAULT 0 NOT NULL,
	FCFRWHOUSE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTOWHOUSE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCAPPROVEB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELICOOR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDAPPROVE datetime DEFAULT NULL NULL,
	FCMSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSUBBR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPLANT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTUPD datetime DEFAULT getdate() NULL,
	FCPRIORITY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCHASCHAIN char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCXFERSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTXFER datetime DEFAULT NULL NULL,
	FMMEMDATA2 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA3 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA4 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCSHOWPLED char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTEPX1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMMEMDATA5 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCTRADETRM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTEDIT datetime DEFAULT NULL NULL,
	FCREASONRQ char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPAYTERM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDREQDATE datetime DEFAULT NULL NULL,
	FCREQMEN char(100) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATEAP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREQPERSN char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNDAYASSUR decimal(8,0) DEFAULT 0 NOT NULL,
	FCISPDPART char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPERSON char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKAPP1 char(12) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKSTP1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKAPP2 char(12) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKSTP2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCOUNTER char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPDBRAND char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRNGTIME char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTRANTYPE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU1ACC char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDATAIMP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRECOMENB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDRECOMENB datetime DEFAULT NULL NULL,
	FMMEMDATA6 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA7 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA8 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA9 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATAA varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCRECALBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASRECAL datetime DEFAULT NULL NULL,
	FCCARTYPE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELIBY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCVEHICLE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTHRDPTY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCROUTEDEL char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDOCSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDOCAPRVB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDDOCAPRV datetime NULL,
	FCCRSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCRAPRVB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDCRAPRV datetime NULL,
	FCU1STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU2STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU1CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCDTYPE2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU2CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU3STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE3 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU3CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU4STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE4 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU4CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU5STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE5 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU5CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU6STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE6 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU6CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU7STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE7 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU7CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU8STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE8 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU8CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU9STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE9 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU9CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCDOCFLOWI char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMDOCFLOW varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCBOICARD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBOIGROUP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCONTACTN char(70) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTSRCUPD datetime NULL,
	FCSRCUPD char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCGID char(128) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCARRIER char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCARRYTYP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELIEMPL char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTATAPPV char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTSTATAPPV datetime DEFAULT getdate() NULL,
	FMEXTRATAG text COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCORGCODE varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCCUACC varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCAPPNAME varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	STATUS_APP int DEFAULT 0 NOT NULL,
	Sendmail int DEFAULT 0 NOT NULL,
	Send_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	Send_Datetime datetime DEFAULT NULL NULL,
	createByEmp char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	editByEmp char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	CONSTRAINT PK__PR_H__8771A646084025CA PRIMARY KEY (FCSKID)
);


-- BUDGET.dbo.Pathfile_PR definition

-- Drop table

-- DROP TABLE BUDGET.dbo.Pathfile_PR;

CREATE TABLE BUDGET.dbo.Pathfile_PR (
	id int IDENTITY(1,1) NOT NULL,
	FCSKIDH nchar(10) COLLATE Thai_CI_AS NULL,
	PR_NO nvarchar(50) COLLATE Thai_CI_AS NULL,
	name_file nvarchar(MAX) COLLATE Thai_CI_AS NULL,
	status_file int DEFAULT 0 NULL,
	[date] datetime NULL,
	Emp nvarchar(50) COLLATE Thai_CI_AS NULL
);


-- BUDGET.dbo.REQUEST_PART definition

-- Drop table

-- DROP TABLE BUDGET.dbo.REQUEST_PART;

CREATE TABLE BUDGET.dbo.REQUEST_PART (
	id int IDENTITY(1,1) NOT NULL,
	dept_request nvarchar(50) COLLATE Thai_CI_AS NULL,
	part_request text COLLATE Thai_CI_AS NULL,
	pu_keyprice numeric(18,2) NULL,
	emp_request nvarchar(50) COLLATE Thai_CI_AS NULL,
	emp_pu nvarchar(50) COLLATE Thai_CI_AS NULL,
	request_datetime datetime NULL,
	keyprice_datetime datetime NULL,
	AC_keypart nvarchar(50) COLLATE Thai_CI_AS NULL,
	AC_emp nvarchar(50) COLLATE Thai_CI_AS NULL,
	AC_keydatetime datetime NULL,
	status int DEFAULT 0 NOT NULL,
	AC_keypartname nvarchar(MAX) COLLATE Thai_CI_AS NULL,
	AC_keyprice numeric(18,2) NULL,
	AC_FCSKID_PROD nvarchar(50) COLLATE Thai_CI_AS NULL,
	UM_FCSKID nvarchar(50) COLLATE Thai_CI_AS NULL,
	UM_CODE nvarchar(50) COLLATE Thai_CI_AS NULL,
	UM_NAME nvarchar(50) COLLATE Thai_CI_AS NULL,
	namefile nvarchar(MAX) COLLATE Thai_CI_AS NULL
);


-- BUDGET.dbo.RT_APPROVE definition

-- Drop table

-- DROP TABLE BUDGET.dbo.RT_APPROVE;

CREATE TABLE BUDGET.dbo.RT_APPROVE (
	id int IDENTITY(1,1) NOT NULL,
	dept_id varchar(50) COLLATE Thai_CI_AS NULL,
	step int NULL,
	email nvarchar(MAX) COLLATE Thai_CI_AS NULL,
	appr_name nvarchar(MAX) COLLATE Thai_CI_AS NULL,
	image_sig nvarchar(MAX) COLLATE Thai_CI_AS NULL,
	ftype int DEFAULT 0 NOT NULL,
	bg_amount numeric(18,4) NULL,
	[position] nvarchar(MAX) COLLATE Thai_CI_AS NULL
);


-- BUDGET.dbo.log_PR_D definition

-- Drop table

-- DROP TABLE BUDGET.dbo.log_PR_D;

CREATE TABLE BUDGET.dbo.log_PR_D (
	id int IDENTITY(1,1) NOT NULL,
	FCDATASER char(4) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSKID char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUDATE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUTIME char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLUPDAPP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTAT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBRANCH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDEPT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSECT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCJOB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCORDERH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDDATE datetime DEFAULT getdate() NOT NULL,
	FCCOOR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFPDTYP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFTYPE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPRODTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSHOWCOMP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCROOTSEQ char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCFORMULAS char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPFORMULA char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPROD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUMSTD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNUMQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNBACKQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNPRICE decimal(20,6) DEFAULT 0 NOT NULL,
	FNDISCAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCPCN decimal(12,2) DEFAULT 0 NOT NULL,
	FCDISCSTR char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSEQ char(4) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATISOUT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNVATRATE decimal(10,1) DEFAULT 0 NOT NULL,
	FNVATAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FCLOT char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCISCHG char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCWHOUSE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMREMARK varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCCTRLSTOC char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATETY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEAFTERR char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSELTAG char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTDATETIME datetime DEFAULT getdate() NOT NULL,
	FIMILLISEC int DEFAULT 0 NOT NULL,
	FCPROJ char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNPRICEKE decimal(20,6) DEFAULT 0 NOT NULL,
	FNDISCAMTK decimal(20,4) DEFAULT 0 NOT NULL,
	FNXRATE decimal(20,8) DEFAULT 0 NOT NULL,
	FMREMARK2 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK3 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK4 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK5 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK6 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK7 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK8 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK9 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMREMARK10 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCIOTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTUM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTUMSTD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNSTUMQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNSTQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FDDELIVERY datetime DEFAULT NULL NULL,
	FCGVPOLICY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCAPPROVEB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDAPPROVE datetime DEFAULT NULL NULL,
	FCSTEP2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCMSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSUBBR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPLANT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTUPD datetime DEFAULT getdate() NULL,
	FCPROCHAIN char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTORE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPRIORITY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCGAG char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMTEXTKE varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FNPRQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FCTXID char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNPLANQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FCPDSTHPAC char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNDEFAPRIC decimal(20,6) DEFAULT 0 NOT NULL,
	FCSUBTXID char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNPACKQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FNDOQTY decimal(20,6) DEFAULT 0 NOT NULL,
	FCACCHART char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPRICE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELITIME char(5) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBUDCHART char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTXIDLINK char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTEDIT datetime DEFAULT NULL NULL,
	FCMAINJOBH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSUBJOBH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATEAP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCOUNTER char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU1ACC char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDATAIMP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRECALBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASRECAL datetime DEFAULT NULL NULL,
	FNWTAXRATE decimal(13,2) DEFAULT 0 NOT NULL,
	FNWTAXAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FNWTAXAMTK decimal(20,4) DEFAULT 0 NOT NULL,
	FCU1STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU2STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU1CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FNU2CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FMERRMSG varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCLID char(10) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBOICARD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBOIGROUP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATEBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORRECTB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTSRCUPD datetime NULL,
	FCSRCUPD char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREMLOCAT char(100) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMEXTRATAG text COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCORGCODE varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCCUACC varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCAPPNAME varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	ADD_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	ADD_Datetime datetime DEFAULT NULL NULL,
	EDIT_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	EDIT_Datetime datetime DEFAULT NULL NULL,
	Cancle_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	Cancle_Datetime datetime DEFAULT NULL NULL
);


-- BUDGET.dbo.log_PR_H definition

-- Drop table

-- DROP TABLE BUDGET.dbo.log_PR_H;

CREATE TABLE BUDGET.dbo.log_PR_H (
	id int IDENTITY(1,1) NOT NULL,
	FCDATASER char(4) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSKID char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUDATE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCUTIME char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLUPDAPP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRFTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFTYPE char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBRANCH char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDEPT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSECT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCJOB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTAT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDDATE datetime DEFAULT getdate() NOT NULL,
	FDDUEDATE datetime DEFAULT NULL NULL,
	FDRECEDATE datetime DEFAULT NULL NULL,
	FCBOOK char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCODE char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREFNO char(35) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNDISCAMT1 decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCAMT2 decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCAMTI decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCPCN1 decimal(12,2) DEFAULT 0 NOT NULL,
	FNDISCPCN2 decimal(12,2) DEFAULT 0 NOT NULL,
	FNDISCPCN3 decimal(12,2) DEFAULT 0 NOT NULL,
	FNAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FNAMT2 decimal(20,4) DEFAULT 0 NOT NULL,
	FCVATISOUT char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATTYPE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNVATRATE decimal(10,1) DEFAULT 0 NOT NULL,
	FNVATAMT decimal(20,4) DEFAULT 0 NOT NULL,
	FCCOOR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEMPL char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEMZONE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCISCASH char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNCREDTERM decimal(10,0) DEFAULT 0 NOT NULL,
	FCCREATEBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCORRECTB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCANCELBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCACSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMMEMDATA varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCHASRET char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCVATDUE char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRECVMAN char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATETY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCEAFTERR char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSELTAG char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTDATETIME datetime DEFAULT getdate() NOT NULL,
	FIMILLISEC int DEFAULT 0 NOT NULL,
	FCSTEP2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPROJ char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDISCSTR char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCURRENCY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNAMTKE decimal(20,4) DEFAULT 0 NOT NULL,
	FNVATAMTKE decimal(20,4) DEFAULT 0 NOT NULL,
	FNDISCAMTK decimal(20,4) DEFAULT 0 NOT NULL,
	FNXRATE decimal(20,8) DEFAULT 0 NOT NULL,
	FCFRWHOUSE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTOWHOUSE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCAPPROVEB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELICOOR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDAPPROVE datetime DEFAULT NULL NULL,
	FCMSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSUBBR char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPLANT char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTUPD datetime DEFAULT getdate() NULL,
	FCPRIORITY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCHASCHAIN char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCXFERSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTXFER datetime DEFAULT NULL NULL,
	FMMEMDATA2 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA3 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA4 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCSHOWPLED char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTEPX1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMMEMDATA5 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCTRADETRM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASTEDIT datetime DEFAULT NULL NULL,
	FCREASONRQ char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPAYTERM char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDREQDATE datetime DEFAULT NULL NULL,
	FCREQMEN char(100) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCREATEAP char(2) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCREQPERSN char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNDAYASSUR decimal(8,0) DEFAULT 0 NOT NULL,
	FCISPDPART char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPERSON char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKAPP1 char(12) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKSTP1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKAPP2 char(12) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCLINKSTP2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCOUNTER char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCPDBRAND char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRNGTIME char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTRANTYPE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU1ACC char(20) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDATAIMP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCRECOMENB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDRECOMENB datetime DEFAULT NULL NULL,
	FMMEMDATA6 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA7 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA8 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATA9 varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FMMEMDATAA varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCRECALBY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTLASRECAL datetime DEFAULT NULL NULL,
	FCCARTYPE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELIBY char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCVEHICLE char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCTHRDPTY char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCROUTEDEL char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDOCSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDOCAPRVB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDDOCAPRV datetime NULL,
	FCCRSTEP char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCRAPRVB char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FDCRAPRV datetime NULL,
	FCU1STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCU2STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE1 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU1CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCDTYPE2 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU2CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU3STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE3 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU3CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU4STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE4 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU4CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU5STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE5 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU5CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU6STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE6 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU6CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU7STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE7 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU7CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU8STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE8 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU8CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCU9STATUS char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDTYPE9 char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FNU9CNT decimal(4,0) DEFAULT 0 NOT NULL,
	FCDOCFLOWI char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FMDOCFLOW varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCBOICARD char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCBOIGROUP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCONTACTN char(70) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTSRCUPD datetime NULL,
	FCSRCUPD char(30) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCGID char(128) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCARRIER char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCCARRYTYP char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCDELIEMPL char(8) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FCSTATAPPV char(1) COLLATE Thai_CI_AS DEFAULT ' ' NOT NULL,
	FTSTATAPPV datetime DEFAULT getdate() NULL,
	FMEXTRATAG text COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCORGCODE varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCCUACC varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	FCAPPNAME varchar(128) COLLATE Thai_CI_AS DEFAULT '' NOT NULL,
	STATUS_APP int DEFAULT 0 NOT NULL,
	Sendmail int DEFAULT 0 NOT NULL,
	Send_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	Send_Datetime datetime DEFAULT NULL NULL,
	ADD_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	ADD_Datetime datetime DEFAULT NULL NULL,
	EDIT_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	EDIT_Datetime datetime DEFAULT NULL NULL,
	Cancle_BY varchar(500) COLLATE Thai_CI_AS DEFAULT NULL NULL,
	Cancle_Datetime datetime DEFAULT NULL NULL
);


-- BUDGET.dbo.log_insert_fomula definition

-- Drop table

-- DROP TABLE BUDGET.dbo.log_insert_fomula;

CREATE TABLE BUDGET.dbo.log_insert_fomula (
	id int IDENTITY(1,1) NOT NULL,
	FCORDERH nvarchar(50) COLLATE Thai_CI_AS NULL,
	FCORDERI nvarchar(50) COLLATE Thai_CI_AS NULL,
	input_date datetime DEFAULT getdate() NULL
);


-- BUDGET.dbo.log_sql definition

-- Drop table

-- DROP TABLE BUDGET.dbo.log_sql;

CREATE TABLE BUDGET.dbo.log_sql (
	id int IDENTITY(1,1) NOT NULL,
	detail nvarchar(MAX) COLLATE Thai_CI_AS NULL,
	order_number nvarchar(50) COLLATE Thai_CI_AS NULL
);


-- BUDGET.dbo.log_step_sendmail definition

-- Drop table

-- DROP TABLE BUDGET.dbo.log_step_sendmail;

CREATE TABLE BUDGET.dbo.log_step_sendmail (
	id int IDENTITY(1,1) NOT NULL,
	FCREFNO nvarchar(50) COLLATE Thai_CI_AS NULL,
	APPROVE_ID nvarchar(50) COLLATE Thai_CI_AS NULL,
	step_id nvarchar(50) COLLATE Thai_CI_AS NULL,
	APPROVE_comment nvarchar(255) COLLATE Thai_CI_AS NULL,
	create_date datetime DEFAULT getdate() NULL,
	REMARK text COLLATE Thai_CI_AS DEFAULT NULL NULL,
	FCBOOK varchar(50) COLLATE Thai_CI_AS NULL
);


-- BUDGET.dbo.status_pr definition

-- Drop table

-- DROP TABLE BUDGET.dbo.status_pr;

CREATE TABLE BUDGET.dbo.status_pr (
	id int NOT NULL,
	Name_statusPR nvarchar(50) COLLATE Thai_CI_AS NULL
);


-- dbo.VMBOOKFM source

CREATE VIEW dbo.VMBOOMFM
AS
SELECT        LTRIM(RTRIM(Formula.dbo.BOOK.FCCODE)) + ' : ' + Formula.dbo.BOOK.FCNAME AS NAME, LTRIM(RTRIM(Formula.dbo.BOOK.FCSKID)) AS FCSKID, Formula.dbo.BOOK.FCREFTYPE
FROM            Formula.dbo.BOOK INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.BOOK.FCCORP
WHERE        (Formula.dbo.BOOK.FCREFTYPE = 'PR') AND (Formula.dbo.BOOK.FCSKID IN ('NR9Z1d02', 'NR9Z1d03'));


-- dbo.VMBOOK_BG source

CREATE VIEW dbo.VMBOOK_BG
AS
SELECT        LTRIM(RTRIM(Formula.dbo.BOOK.FCCODE)) + ' : ' + Formula.dbo.BOOK.FCNAME AS NAME, LTRIM(RTRIM(Formula.dbo.BOOK.FCSKID)) AS FCSKID
FROM            Formula.dbo.BOOK INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.BOOK.FCCORP
WHERE        (Formula.dbo.BOOK.FCREFTYPE = 'PR') AND (Formula.dbo.BOOK.FCSKID = 'NR9Z1d02');


-- dbo.VMBOOK_BG21 source

CREATE VIEW dbo.VMBOOK_BG21
AS
SELECT        LTRIM(RTRIM(Formula.dbo.BOOK.FCCODE)) + ' : ' + Formula.dbo.BOOK.FCNAME AS NAME, LTRIM(RTRIM(Formula.dbo.BOOK.FCSKID)) AS FCSKID
FROM            Formula.dbo.BOOK INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.BOOK.FCCORP
WHERE        (Formula.dbo.BOOK.FCREFTYPE = 'PR') AND (Formula.dbo.BOOK.FCSKID = 'NR9Z1d02');


-- dbo.VMBOOK_NOBG source

CREATE VIEW dbo.VMBOOK_NOBG
AS
SELECT        LTRIM(RTRIM(Formula.dbo.BOOK.FCCODE)) + ' : ' + Formula.dbo.BOOK.FCNAME AS NAME, LTRIM(RTRIM(Formula.dbo.BOOK.FCSKID)) AS FCSKID
FROM            Formula.dbo.BOOK INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.BOOK.FCCORP
WHERE        (Formula.dbo.BOOK.FCREFTYPE = 'PR') AND (Formula.dbo.BOOK.FCSKID = 'NR9Z1d03');


-- dbo.VMBOOK_NOBG21 source

CREATE VIEW dbo.VMBOOK_NOBG21
AS
SELECT        LTRIM(RTRIM(Formula.dbo.BOOK.FCCODE)) + ' : ' + Formula.dbo.BOOK.FCNAME AS NAME, LTRIM(RTRIM(Formula.dbo.BOOK.FCSKID)) AS FCSKID
FROM            Formula.dbo.BOOK INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.BOOK.FCCORP
WHERE        (Formula.dbo.BOOK.FCREFTYPE = 'PR') AND (Formula.dbo.BOOK.FCSKID = 'NR9Z1d03');


-- dbo.VMBRANCH source

CREATE VIEW dbo.VMBRANCH
AS
SELECT        Formula.dbo.BRANCH.FCDATASER, Formula.dbo.BRANCH.FCSKID, Formula.dbo.BRANCH.FCUDATE, Formula.dbo.BRANCH.FCUTIME, Formula.dbo.BRANCH.FCLUPDAPP, Formula.dbo.BRANCH.FCBAKYRHIS, 
                         Formula.dbo.BRANCH.FCCORP, Formula.dbo.BRANCH.FCCODE, Formula.dbo.BRANCH.FCNAME, Formula.dbo.BRANCH.FCNAME2, Formula.dbo.BRANCH.FCDEFAPRIN, Formula.dbo.BRANCH.FCADDR1, 
                         Formula.dbo.BRANCH.FCADDR2, Formula.dbo.BRANCH.FCADDR12, Formula.dbo.BRANCH.FCADDR22, Formula.dbo.BRANCH.FCTEL, Formula.dbo.BRANCH.FCFAX, Formula.dbo.BRANCH.FDLASTCLOS, Formula.dbo.BRANCH.FCSEQ, 
                         Formula.dbo.BRANCH.FDLASTDELE, Formula.dbo.BRANCH.FCWHBUY, Formula.dbo.BRANCH.FCWHSALE, Formula.dbo.BRANCH.FCMACHINEN, Formula.dbo.BRANCH.FCBAKDIRNA, Formula.dbo.BRANCH.FCLBDATASE, 
                         Formula.dbo.BRANCH.FCCREATETY, Formula.dbo.BRANCH.FCEAFTERR, Formula.dbo.BRANCH.FCPATSTEP, Formula.dbo.BRANCH.FCSELTAG, Formula.dbo.BRANCH.FTDATETIME, Formula.dbo.BRANCH.FIMILLISEC, 
                         Formula.dbo.BRANCH.FCFCHR, Formula.dbo.BRANCH.FCHCODE, Formula.dbo.BRANCH.FCCOSTBASE, Formula.dbo.BRANCH.FCPPOLIBY, Formula.dbo.BRANCH.FCREALCUST, Formula.dbo.BRANCH.FCADDR3, 
                         Formula.dbo.BRANCH.FCADDR32, Formula.dbo.BRANCH.FCSUBBR, Formula.dbo.BRANCH.FCVCHCOOR, Formula.dbo.BRANCH.FCDXCODE, Formula.dbo.BRANCH.FCPAYINVCT, Formula.dbo.BRANCH.FCAPVSOTYP, 
                         Formula.dbo.BRANCH.FCAPVPRTYP, Formula.dbo.BRANCH.FCAPVPOTYP, Formula.dbo.BRANCH.FCSHOWVCHT, Formula.dbo.BRANCH.FCVCHBILL, Formula.dbo.BRANCH.FCGLCURR, Formula.dbo.BRANCH.FCPAYINFEE, 
                         Formula.dbo.BRANCH.FCBPRCTYPE, Formula.dbo.BRANCH.FCSPRCTYPE, Formula.dbo.BRANCH.FTLASTUPD, Formula.dbo.BRANCH.FCAPVQSTYP, Formula.dbo.BRANCH.FCSHOWDRCR, Formula.dbo.BRANCH.FCAPVSITYP, 
                         Formula.dbo.BRANCH.FCLID, Formula.dbo.BRANCH.FTLASTEDIT, Formula.dbo.BRANCH.FCU1STATUS, Formula.dbo.BRANCH.FCU2STATUS, Formula.dbo.BRANCH.FCDTYPE1, Formula.dbo.BRANCH.FCDTYPE2, 
                         Formula.dbo.BRANCH.FCBKACCPAY, Formula.dbo.BRANCH.FCSERVEVAT, Formula.dbo.BRANCH.FNU1CNT, Formula.dbo.BRANCH.FNU2CNT, Formula.dbo.BRANCH.FMERRMSG, Formula.dbo.BRANCH.FCCREATEAP, 
                         Formula.dbo.BRANCH.FCFRONTAUD, Formula.dbo.BRANCH.FCSTATUS, Formula.dbo.BRANCH.FCSDNAME, Formula.dbo.BRANCH.FDINACTIVE, Formula.dbo.BRANCH.FCSECTITEM, Formula.dbo.BRANCH.FCSECTBILL, 
                         Formula.dbo.BRANCH.FCFRONTLOC, Formula.dbo.BRANCH.FCU1ACC, Formula.dbo.BRANCH.FCDATAIMP, Formula.dbo.BRANCH.FCREVACCBK, Formula.dbo.BRANCH.FCMANFLAG, Formula.dbo.BRANCH.FCADDAPVBY, 
                         Formula.dbo.BRANCH.FCEDTAPVBY, Formula.dbo.BRANCH.FCDELAPVBY, Formula.dbo.BRANCH.FCISUSED, Formula.dbo.BRANCH.FCCHKMPRC, Formula.dbo.BRANCH.FCCREATEBY, Formula.dbo.BRANCH.FCCORRECTB, 
                         Formula.dbo.BRANCH.FCU3STATUS, Formula.dbo.BRANCH.FCDTYPE3, Formula.dbo.BRANCH.FNU3CNT, Formula.dbo.BRANCH.FCU4STATUS, Formula.dbo.BRANCH.FCDTYPE4, Formula.dbo.BRANCH.FNU4CNT, 
                         Formula.dbo.BRANCH.FCU5STATUS, Formula.dbo.BRANCH.FCDTYPE5, Formula.dbo.BRANCH.FNU5CNT, Formula.dbo.BRANCH.FCU6STATUS, Formula.dbo.BRANCH.FCDTYPE6, Formula.dbo.BRANCH.FNU6CNT, 
                         Formula.dbo.BRANCH.FCU7STATUS, Formula.dbo.BRANCH.FCDTYPE7, Formula.dbo.BRANCH.FNU7CNT, Formula.dbo.BRANCH.FCU8STATUS, Formula.dbo.BRANCH.FCDTYPE8, Formula.dbo.BRANCH.FNU8CNT, 
                         Formula.dbo.BRANCH.FCU9STATUS, Formula.dbo.BRANCH.FCDTYPE9, Formula.dbo.BRANCH.FNU9CNT, Formula.dbo.BRANCH.FCPOSTCNTY, Formula.dbo.BRANCH.FCGLBILLAP, Formula.dbo.BRANCH.FCGLBILLAR, 
                         Formula.dbo.BRANCH.FCPYMRUNTY, Formula.dbo.BRANCH.FNPYMRUNL, Formula.dbo.BRANCH.FCGID, Formula.dbo.BRANCH.FCSENDETAX, Formula.dbo.BRANCH.FTSRCUPD, Formula.dbo.BRANCH.FCSRCUPD, 
                         Formula.dbo.BRANCH.FMEXTRATAG, Formula.dbo.BRANCH.FCORGCODE, Formula.dbo.BRANCH.FCCUACC, Formula.dbo.BRANCH.FCAPPNAME
FROM            Formula.dbo.BRANCH INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.BRANCH.FCCORP
WHERE        (Formula.dbo.BRANCH.FCSKID = 'NOPctb01');


-- dbo.VMCOOR source

CREATE VIEW dbo.VMCOOR
AS
SELECT        Formula.dbo.COOR.FCCODE, Formula.dbo.COOR.FCNAME, Formula.dbo.COOR.FCSKID, Formula.dbo.COOR.FCISSUPP, Formula.dbo.COOR.FCCORP
FROM            Formula.dbo.COOR INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.COOR.FCCORP
WHERE        (Formula.dbo.COOR.FCISSUPP = 'Y') AND (Formula.dbo.COOR.FCCODE = 'VCS') AND (Formula.dbo.COOR.FCCODE <> '-');


-- dbo.VMCORP source

/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW dbo.VMCORP
AS
SELECT        Formula.dbo.CORP.FCDATASER, Formula.dbo.CORP.FCSKID, Formula.dbo.CORP.FCUDATE, Formula.dbo.CORP.FCUTIME, Formula.dbo.CORP.FCLUPDAPP, Formula.dbo.CORP.FCBAKYRHIS, Formula.dbo.CORP.FCCODE, 
                         Formula.dbo.CORP.FCNAME, Formula.dbo.CORP.FCNAME2, Formula.dbo.CORP.FCTAXID, Formula.dbo.CORP.FCADDR1, Formula.dbo.CORP.FCADDR12, Formula.dbo.CORP.FCADDR2, Formula.dbo.CORP.FCADDR22, 
                         Formula.dbo.CORP.FCTEL, Formula.dbo.CORP.FCFAX, Formula.dbo.CORP.FDUSERDATE, Formula.dbo.CORP.FDCALDATE, Formula.dbo.CORP.FCBACCDATE, Formula.dbo.CORP.FCBACCMTH, Formula.dbo.CORP.FNROUNDDEP, 
                         Formula.dbo.CORP.FCACCBOOK, Formula.dbo.CORP.FDCPBEGDAT, Formula.dbo.CORP.FDCPENDDAT, Formula.dbo.CORP.FCBRANCHIS, Formula.dbo.CORP.FCBRANCHI2, Formula.dbo.CORP.FCDEPTIS, 
                         Formula.dbo.CORP.FCDEPTIS2, Formula.dbo.CORP.FCSECTIS, Formula.dbo.CORP.FCSECTIS2, Formula.dbo.CORP.FCCTRLSTOC, Formula.dbo.CORP.FCGOODSTYP, Formula.dbo.CORP.FCRAWTYPE, 
                         Formula.dbo.CORP.FCSEMITYPE, Formula.dbo.CORP.FCGOODSCOS, Formula.dbo.CORP.FCRAWCOST, Formula.dbo.CORP.FCSEMICOST, Formula.dbo.CORP.FCVATISOUT, Formula.dbo.CORP.FCVATTYPE, 
                         Formula.dbo.CORP.FNVATRATE, Formula.dbo.CORP.FCSHOWCOMP, Formula.dbo.CORP.FCEDPRICE, Formula.dbo.CORP.FCEDNAME, Formula.dbo.CORP.FCEDCOMPO, Formula.dbo.CORP.FCARNDUE, 
                         Formula.dbo.CORP.FCAROVER, Formula.dbo.CORP.FCAPNDUE, Formula.dbo.CORP.FCAPOVER, Formula.dbo.CORP.FCAMTPICT, Formula.dbo.CORP.FCVATPICT, Formula.dbo.CORP.FCPRICEPIC, Formula.dbo.CORP.FCQTYPICT, 
                         Formula.dbo.CORP.FCCORPCHAR, Formula.dbo.CORP.FMMEMDATA, Formula.dbo.CORP.FNSELL1PCT, Formula.dbo.CORP.FNSELL2PCT, Formula.dbo.CORP.FNSELL3PCT, Formula.dbo.CORP.FNSELL4PCT, 
                         Formula.dbo.CORP.FCSECURMOD, Formula.dbo.CORP.FCTYNAMECO, Formula.dbo.CORP.FCTYNAMEPR, Formula.dbo.CORP.FNDECLIMIT, Formula.dbo.CORP.FNDECLIM2, Formula.dbo.CORP.FNDECLIM3, 
                         Formula.dbo.CORP.FNDECLIM4, Formula.dbo.CORP.FCCREATETY, Formula.dbo.CORP.FCEAFTERR, Formula.dbo.CORP.FCSELTAG, Formula.dbo.CORP.FTDATETIME, Formula.dbo.CORP.FIMILLISEC, Formula.dbo.CORP.FCPLTYPE, 
                         Formula.dbo.CORP.FCTYPE, Formula.dbo.CORP.FCCOMMERCI, Formula.dbo.CORP.FCFCHR, Formula.dbo.CORP.FCSECT, Formula.dbo.CORP.FCDEPT, Formula.dbo.CORP.FCJOB, Formula.dbo.CORP.FCSWCAT, 
                         Formula.dbo.CORP.FCHCODE, Formula.dbo.CORP.FCPROJ, Formula.dbo.CORP.FCPROJIS, Formula.dbo.CORP.FCPROJIS2, Formula.dbo.CORP.FCJOBIS, Formula.dbo.CORP.FCJOBIS2, Formula.dbo.CORP.FCCORPIS, 
                         Formula.dbo.CORP.FCCORPIS2, Formula.dbo.CORP.FDBUDGDATE, Formula.dbo.CORP.FCSUBBRIS, Formula.dbo.CORP.FCSUBBRIS2, Formula.dbo.CORP.FMMEMDATA2, Formula.dbo.CORP.FCDXCODE, 
                         Formula.dbo.CORP.FCHOLDER, Formula.dbo.CORP.FCSTOCKAGE, Formula.dbo.CORP.FNBUDYR, Formula.dbo.CORP.FCCURRENCY, Formula.dbo.CORP.FCTRADENO, Formula.dbo.CORP.FCSTDCURR, 
                         Formula.dbo.CORP.FTLASTUPD, Formula.dbo.CORP.FCMCTRLSTO, Formula.dbo.CORP.FCLID, Formula.dbo.CORP.FTLASTEDIT, Formula.dbo.CORP.FCU1STATUS, Formula.dbo.CORP.FCU2STATUS, Formula.dbo.CORP.FCDTYPE1, 
                         Formula.dbo.CORP.FCDTYPE2, Formula.dbo.CORP.FNU1CNT, Formula.dbo.CORP.FNU2CNT, Formula.dbo.CORP.FMERRMSG, Formula.dbo.CORP.FCSTATUS, Formula.dbo.CORP.FDINACTIVE, Formula.dbo.CORP.FCCREATEAP, 
                         Formula.dbo.CORP.FCSDNAME, Formula.dbo.CORP.FCPVKEY, Formula.dbo.CORP.FCDSSDNAME, Formula.dbo.CORP.FNCHGPASSW, Formula.dbo.CORP.FNWITHCHG, Formula.dbo.CORP.FNLOCKDATE, 
                         Formula.dbo.CORP.FCSHOWROP, Formula.dbo.CORP.FCU1ACC, Formula.dbo.CORP.FCDATAIMP, Formula.dbo.CORP.FCBKCORPID, Formula.dbo.CORP.FCMANFLAG, Formula.dbo.CORP.FCADDAPVBY, 
                 Formula.dbo.CORP.FCEDTAPVBY, Formula.dbo.CORP.FCDELAPVBY, Formula.dbo.CORP.FCISUSED, Formula.dbo.CORP.FDBGPERIOD, Formula.dbo.CORP.FCBGPERIOD, Formula.dbo.CORP.FCHOLDCORP, 
                         Formula.dbo.CORP.FNHSHARES, Formula.dbo.CORP.FNTSHARES, Formula.dbo.CORP.FCFREECORP, Formula.dbo.CORP.FCPDSHARE, Formula.dbo.CORP.FCACCSHARE, Formula.dbo.CORP.FNTAXBEG1, 
                         Formula.dbo.CORP.FNTAXEND1, Formula.dbo.CORP.FNTAXRATE1, Formula.dbo.CORP.FNTAXBEG2, Formula.dbo.CORP.FNTAXEND2, Formula.dbo.CORP.FNTAXRATE2, Formula.dbo.CORP.FNTAXBEG3, 
                         Formula.dbo.CORP.FNTAXEND3, Formula.dbo.CORP.FNTAXRATE3, Formula.dbo.CORP.FNTAXBEG4, Formula.dbo.CORP.FNTAXEND4, Formula.dbo.CORP.FNTAXRATE4, Formula.dbo.CORP.FNTAXBEG5, 
                         Formula.dbo.CORP.FNTAXEND5, Formula.dbo.CORP.FNTAXRATE5, Formula.dbo.CORP.FCU3STATUS, Formula.dbo.CORP.FCDTYPE3, Formula.dbo.CORP.FNU3CNT, Formula.dbo.CORP.FCU4STATUS, Formula.dbo.CORP.FCDTYPE4, 
                         Formula.dbo.CORP.FNU4CNT, Formula.dbo.CORP.FCU5STATUS, Formula.dbo.CORP.FCDTYPE5, Formula.dbo.CORP.FNU5CNT, Formula.dbo.CORP.FCU6STATUS, Formula.dbo.CORP.FCDTYPE6, Formula.dbo.CORP.FNU6CNT, 
                         Formula.dbo.CORP.FCU7STATUS, Formula.dbo.CORP.FCDTYPE7, Formula.dbo.CORP.FNU7CNT, Formula.dbo.CORP.FCU8STATUS, Formula.dbo.CORP.FCDTYPE8, Formula.dbo.CORP.FNU8CNT, Formula.dbo.CORP.FCU9STATUS, 
                         Formula.dbo.CORP.FCDTYPE9, Formula.dbo.CORP.FNU9CNT, Formula.dbo.CORP.FCCNCOSTS, Formula.dbo.CORP.FCCNCOSTB, Formula.dbo.CORP.FCCOSTZERO, Formula.dbo.CORP.FNCOSTZERO, 
                         Formula.dbo.CORP.FCCOSTACNT, Formula.dbo.CORP.FNCOSTACNT, Formula.dbo.CORP.FCCOSTRETW, Formula.dbo.CORP.FNCOSTRETW, Formula.dbo.CORP.FCPERIODTY, Formula.dbo.CORP.FCBOICARD, 
                         Formula.dbo.CORP.FCBOIGROUP, Formula.dbo.CORP.FCCREATEBY, Formula.dbo.CORP.FCCORRECTB, Formula.dbo.CORP.FCCOSTBTYP, Formula.dbo.CORP.FCVATREG, Formula.dbo.CORP.FCCODEONL, 
                         Formula.dbo.CORP.FTSRCUPD, Formula.dbo.CORP.FCSRCUPD, Formula.dbo.CORP.FCGID, Formula.dbo.CORP.FCLOCKTRAN, Formula.dbo.CORP.FCNO, Formula.dbo.CORP.FCFLOOR, Formula.dbo.CORP.FCROOMNO, 
                         Formula.dbo.CORP.FCBUILDING, Formula.dbo.CORP.FCBUILDIN2, Formula.dbo.CORP.FCMOO, Formula.dbo.CORP.FCSOI, Formula.dbo.CORP.FCSOI2, Formula.dbo.CORP.FCROAD, Formula.dbo.CORP.FCROAD2, 
                         Formula.dbo.CORP.FCQCJANGWA, Formula.dbo.CORP.FCQNJANGWA, Formula.dbo.CORP.FCQNJANGW2, Formula.dbo.CORP.FCQCAMPHUR, Formula.dbo.CORP.FCQNAMPHUR, Formula.dbo.CORP.FCQNAMPHU2, 
                         Formula.dbo.CORP.FCQCTAMBON, Formula.dbo.CORP.FCQNTAMBON, Formula.dbo.CORP.FCQNTAMBO2, Formula.dbo.CORP.FCZIP, Formula.dbo.CORP.FCEMAIL, Formula.dbo.CORP.FCQCCOUNTY, 
                         Formula.dbo.CORP.FCSHOW2UM, Formula.dbo.CORP.FCCHGDUE, Formula.dbo.CORP.FMEXTRATAG, Formula.dbo.CORP.FCORGCODE, Formula.dbo.CORP.FCCUACC, Formula.dbo.CORP.FCAPPNAME, 
                         Formula.dbo.BRANCH.FCNAME AS NAME_BRANCH
FROM            Formula.dbo.CORP INNER JOIN
                         Formula.dbo.BRANCH ON Formula.dbo.BRANCH.FCCORP = Formula.dbo.CORP.FCSKID
WHERE        (Formula.dbo.CORP.FCCODE = '0001');


-- dbo.VMDEPT source

CREATE VIEW dbo.VMDEPT
AS
SELECT        Formula.dbo.DEPT.FCSKID, Formula.dbo.DEPT.FCCODE, Formula.dbo.DEPT.FCNAME, Formula.dbo.DEPT.FCNAME2
FROM            Formula.dbo.DEPT INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.DEPT.FCCORP
WHERE        (Formula.dbo.DEPT.FCCODE <> '-');


-- dbo.VMMODEL_DPRBG source

CREATE VIEW dbo.VMMODEL_DPRBG
AS
SELECT        FCDATASER, FCSKID, FCUDATE, FCUTIME, FCLUPDAPP, FCSTAT, FCSTEP, FCCORP, FCBRANCH, FCDEPT, FCSECT, FCJOB, FCORDERH, FDDATE, FCCOOR, FCREFPDTYP, FCREFTYPE, FCPRODTYPE, FCSHOWCOMP, 
                         FCROOTSEQ, FCFORMULAS, FCPFORMULA, FCPROD, FCUM, FCUMSTD, FNUMQTY, FNQTY, FNBACKQTY, FNPRICE, FNDISCAMT, FNDISCPCN, FCDISCSTR, FCSEQ, FCVATISOUT, FCVATTYPE, FNVATRATE, FNVATAMT, FCLOT, 
                         FCISCHG, FCWHOUSE, FMREMARK, FCCTRLSTOC, FCCREATETY, FCEAFTERR, FCSELTAG, FTDATETIME, FIMILLISEC, FCPROJ, FNPRICEKE, FNDISCAMTK, FNXRATE, FMREMARK2, FMREMARK3, FMREMARK4, FMREMARK5, 
                         FMREMARK6, FMREMARK7, FMREMARK8, FMREMARK9, FMREMARK10, FCIOTYPE, FCSTUM, FCSTUMSTD, FNSTUMQTY, FNSTQTY, FDDELIVERY, FCGVPOLICY, FCAPPROVEB, FDAPPROVE, FCSTEP2, FCMSTEP, FCSUBBR, 
                         FCPLANT, FTLASTUPD, FCPROCHAIN, FCSTORE, FCPRIORITY, FCGAG, FMTEXTKE, FNPRQTY, FCTXID, FNPLANQTY, FCPDSTHPAC, FNDEFAPRIC, FCSUBTXID, FNPACKQTY, FNDOQTY, FCACCHART, FCPRICE, FCDELITIME, 
                         FCBUDCHART, FCTXIDLINK, FTLASTEDIT, FCMAINJOBH, FCSUBJOBH, FCCREATEAP, FCCOUNTER, FCU1ACC, FCDATAIMP, FCRECALBY, FTLASRECAL, FNWTAXRATE, FNWTAXAMT, FNWTAXAMTK, FCU1STATUS, FCU2STATUS, 
                         FCDTYPE1, FCDTYPE2, FNU1CNT, FNU2CNT, FMERRMSG, FCLID, FCCREATEBY, FCCORRECTB, FCBOICARD, FCBOIGROUP
FROM            Formula.dbo.ORDERI
WHERE        (FCORDERH = 'Nw2U1X01');


-- dbo.VMMODEL_PRBG source

CREATE VIEW dbo.VMMODEL_PRBG
AS
SELECT        FCDATASER, FCSKID, FCUDATE, FCUTIME, FCLUPDAPP, FCRFTYPE, FCREFTYPE, FCCORP, FCBRANCH, FCDEPT, FCSECT, FCJOB, FCSTAT, FCSTEP, FDDATE, FDDUEDATE, FDRECEDATE, FCBOOK, FCCODE, FCREFNO, 
                         FNDISCAMT1, FNDISCAMT2, FNDISCAMTI, FNDISCPCN1, FNDISCPCN2, FNDISCPCN3, FNAMT, FNAMT2, FCVATISOUT, FCVATTYPE, FNVATRATE, FNVATAMT, FCCOOR, FCEMPL, FCEMZONE, FCISCASH, FNCREDTERM, 
                         FCCREATEBY, FCCORRECTB, FCCANCELBY, FCACSTEP, FMMEMDATA, FCHASRET, FCVATDUE, FCRECVMAN, FCCREATETY, FCEAFTERR, FCSELTAG, FTDATETIME, FIMILLISEC, FCSTEP2, FCPROJ, FCDISCSTR, FCCURRENCY, 
                         FNAMTKE, FNVATAMTKE, FNDISCAMTK, FNXRATE, FCFRWHOUSE, FCTOWHOUSE, FCAPPROVEB, FCDELICOOR, FDAPPROVE, FCMSTEP, FCSUBBR, FCPLANT, FTLASTUPD, FCPRIORITY, FCHASCHAIN, FCXFERSTEP, FTXFER, 
                         FMMEMDATA2, FMMEMDATA3, FMMEMDATA4, FCSHOWPLED, FCSTEPX1, FMMEMDATA5, FCTRADETRM, FTLASTEDIT, FCREASONRQ, FCPAYTERM, FDREQDATE, FCREQMEN, FCCREATEAP, FCREQPERSN, FNDAYASSUR, 
                         FCISPDPART, FCPERSON, FCLINKAPP1, FCLINKSTP1, FCLINKAPP2, FCLINKSTP2, FCCOUNTER, FCPDBRAND, FCRNGTIME, FCTRANTYPE, FCU1ACC, FCDATAIMP, FCRECOMENB, FDRECOMENB, FMMEMDATA6, FMMEMDATA7, 
                         FMMEMDATA8, FMMEMDATA9, FMMEMDATAA, FCRECALBY, FTLASRECAL, FCCARTYPE, FCDOCSTEP, FCDOCAPRVB, FDDOCAPRV, FCCRSTEP, FCCRAPRVB, FDCRAPRV, FCU1STATUS, FCU2STATUS, FCDELIBY, FCCVEHICLE, 
                         FCTHRDPTY, FCROUTEDEL, FCDTYPE1, FNU1CNT, FCDTYPE2, FNU2CNT, FCU3STATUS, FCDTYPE3, FNU3CNT, FCU4STATUS, FCDTYPE4, FNU4CNT, FCU5STATUS, FCDTYPE5, FNU5CNT, FCU6STATUS, FCDTYPE6, FNU6CNT, 
                         FCU7STATUS, FCDTYPE7, FNU7CNT, FCU8STATUS, FCDTYPE8, FNU8CNT, FCU9STATUS, FCDTYPE9, FNU9CNT, FCDOCFLOWI, FMDOCFLOW, FCBOICARD, FCBOIGROUP, FCCONTACTN
FROM            Formula.dbo.ORDERH
WHERE        (FCCODE = '0000001') AND (FCREFNO = 'PRTEST01');


-- dbo.VMPR source

CREATE VIEW dbo.VMPR
AS
SELECT        Formula.dbo.ORDERH.FCREFNO, Formula.dbo.ORDERH.FDDATE, Formula.dbo.ORDERH.FCDEPT, CASE WHEN LEN(Formula.dbo.ORDERH.FMMEMDATA) > 0 THEN SUBSTRING(Formula.dbo.ORDERH.FMMEMDATA, 5, 
                         LTRIM(RTRIM(LEN(Formula.dbo.ORDERH.FMMEMDATA))) - 8) ELSE '' END AS FMMEMDATA, Formula.dbo.ORDERH.FCSTEP, Formula.dbo.ORDERI.FCPROD, Formula.dbo.ORDERI.FMREMARK, Formula.dbo.ORDERI.FNQTY, 
                         Formula.dbo.ORDERI.FNPRICE, Formula.dbo.ORDERI.FNQTY * Formula.dbo.ORDERI.FNPRICE AS total, Formula.dbo.ORDERI.FDDATE AS duedate, Formula.dbo.ORDERI.FMREMARK2, dbo.VMPROD_PRICE.FCNAME, 
                         dbo.VMPROD_PRICE.FCCODE, dbo.VMPROD_PRICE.UNIT, dbo.vm_dept.FCNAME AS DEPTNAME, Formula.dbo.ORDERH.FNAMT, Formula.dbo.ORDERH.FNVATAMT, 
                         Formula.dbo.ORDERH.FNAMT + Formula.dbo.ORDERH.FNVATAMT AS TOTALAMT
FROM            Formula.dbo.ORDERH INNER JOIN
                         Formula.dbo.ORDERI ON Formula.dbo.ORDERI.FCORDERH = Formula.dbo.ORDERH.FCSKID INNER JOIN
                         dbo.VMPROD_PRICE ON dbo.VMPROD_PRICE.FCSKID = Formula.dbo.ORDERI.FCPROD INNER JOIN
                         dbo.vm_dept ON dbo.vm_dept.FCSKIDSECT = Formula.dbo.ORDERH.FCSECT
WHERE        (Formula.dbo.ORDERH.FCREFTYPE = 'PR');


-- dbo.VMPROD_PRICE source

CREATE VIEW dbo.VMPROD_PRICE
AS
SELECT        Formula.dbo.PROD.FCSKID, Formula.dbo.PROD.FCCODE, Formula.dbo.PROD.FCSNAME, Formula.dbo.PROD.FCNAME, ISNULL(Formula.dbo.PROD.FNSTDCOST, '1') AS FNPRICE, Formula.dbo.PROD.FCTYPE, 
                         SUBSTRING(SUBSTRING(Formula.dbo.PRODX4.FMMEMDATA, 6, LEN(Formula.dbo.PRODX4.FMMEMDATA)), - 8, LEN(Formula.dbo.PRODX4.FMMEMDATA)) + ' PCS/ ' + SUBSTRING(SUBSTRING(Formula.dbo.PRODX4.FMMEMDATA2,
                          5, LEN(Formula.dbo.PRODX4.FMMEMDATA2)), - 7, LEN(Formula.dbo.PRODX4.FMMEMDATA2)) AS packcode, Formula.dbo.UM.FCNAME AS UNIT, Formula.dbo.UM.FCSKID AS FCUM
FROM            Formula.dbo.PROD INNER JOIN
                         Formula.dbo.UM ON Formula.dbo.UM.FCSKID = Formula.dbo.PROD.FCUM LEFT OUTER JOIN
                         Formula.dbo.PRODX4 ON Formula.dbo.PRODX4.FCPROD = Formula.dbo.PROD.FCSKID INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.PROD.FCCORP
GROUP BY Formula.dbo.PROD.FCSKID, Formula.dbo.PROD.FCCODE, Formula.dbo.PROD.FCSNAME, Formula.dbo.PROD.FCNAME, Formula.dbo.PROD.FCTYPE, Formula.dbo.PRODX4.FMMEMDATA2, Formula.dbo.PROD.FNSTDCOST, 
                         Formula.dbo.PRODX4.FMMEMDATA, Formula.dbo.UM.FCNAME, Formula.dbo.UM.FCSKID;


-- dbo.VM_UNIT source

CREATE VIEW dbo.VM_UNIT
AS
SELECT        Formula.dbo.UM.FCSKID, Formula.dbo.UM.FCSTAT, Formula.dbo.UM.FCCORP, Formula.dbo.UM.FCCODE, Formula.dbo.UM.FCNAME, Formula.dbo.UM.FCNAME2, Formula.dbo.UM.FCTYPE
FROM            Formula.dbo.UM INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.UM.FCCORP;


-- dbo.vm_dept source

CREATE VIEW dbo.vm_dept
AS
SELECT        Formula.dbo.SECT.FCSKID AS FCSKIDSECT, Formula.dbo.DEPT.FCSKID AS FCSKIDDEPT, Formula.dbo.SECT.FCCODE, Formula.dbo.SECT.FCNAME, 
                         CASE WHEN Formula.dbo.DEPT.FCNAME2 = '<NOT SPECIFIED>' THEN 'EX' ELSE Formula.dbo.DEPT.FCNAME2 END AS FCNAME2
FROM            Formula.dbo.SECT INNER JOIN
                         Formula.dbo.DEPT ON Formula.dbo.DEPT.FCSKID = Formula.dbo.SECT.FCDEPT INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.SECT.FCCORP
WHERE        (Formula.dbo.SECT.FCCODE <> '-') AND (Formula.dbo.SECT.FCSTATUS = '');


-- dbo.vmlogin source

CREATE VIEW dbo.vmlogin
AS
SELECT        Formula.dbo.EMPLR.FCLOGIN, Formula.dbo.EMPLR.FCPW, Formula.dbo.EMPLR.FCRCODE, Formula.dbo.POST.FCCODE, Formula.dbo.POST.FCNAME
FROM            Formula.dbo.EMPLR INNER JOIN
                         Formula.dbo.EMPL ON Formula.dbo.EMPL.FCRCODE = Formula.dbo.EMPLR.FCRCODE INNER JOIN
                         Formula.dbo.EMPPOST ON Formula.dbo.EMPPOST.FCEMPL = Formula.dbo.EMPL.FCSKID INNER JOIN
                         Formula.dbo.POST ON Formula.dbo.POST.FCSKID = Formula.dbo.EMPPOST.FCPOST INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.EMPL.FCCORP;


-- dbo.vmprod source

CREATE VIEW dbo.vmprod
AS
SELECT DISTINCT Formula.dbo.PROD.FCSKID, Formula.dbo.PROD.FCCODE, Formula.dbo.PROD.FCSNAME, Formula.dbo.PROD.FCNAME, Formula.dbo.PROD.FNSTDCOST AS FNPRICE, '' AS SUP_CODE,
                             (SELECT        MAX(FDDATE) AS Expr1
                               FROM            Formula.dbo.REFPROD
                               WHERE        (FCPROD = dbo.VMCORP.FCSKID)
                               GROUP BY FCPROD) AS DDATE
FROM            Formula.dbo.PROD INNER JOIN
                         dbo.VMCORP ON dbo.VMCORP.FCSKID = Formula.dbo.PROD.FCCORP
WHERE        (Formula.dbo.PROD.FCTYPE IN ('1', '2', '3', '4', '5', '6', '8', '9'));


